### ISSUE TITLE
Functionality now in core?

### ISSUE THREAD

**Issue by magnolia61** [lcdservices/biz.lcdservices.moveparticipant#1]
A few questions :-)

Is this functionality now more or less in core? And is the functionality of this extension kind of the same as https://github.com/JMAConsulting/biz.jmaconsulting.transferevent ?

What I am looking for is actually a way to change a registration to a different event.
Contact A is registered to event 1. But changes his mind and wants to change it to event 2.
Would this extension be a good base to extend on that?

Kind regards,
Richard

**Comment by lcdservices** [comment]
It looks like the JMA extension takes an existing registration, puts it in 'transferred' status, and creates a new registration for the selected event. It seems to be closer to what you're looking for.

My extension moves the registration as-is to a different contact. This is similar to the core functionality to transfer to a different registrant, but the behavior/data handling is a bit different. My extension is more simple and straightforward with the "move."

**Comment by magnolia61** [comment]
Thanks for the explanation Brian. The transferevent extension is a little too fancy for what I am looking for. Actually I'm only looking for an easy way to change event_id in civicrm_participant to attach the registration to a different event. Kind of like the attach contribution extension :-)
