### ISSUE TITLE
Error: Call to undefined method CRM_Core_OptionGroup::getValue() 

### ISSUE THREAD

**Issue by magnolia61** [lcdservices/biz.lcdservices.moveparticipant#2]
Hi Brian,
Just upgraded to CiviCRM 5.66 and got an error message using moveparticipant.
The move windows gets stuck forerver greyed out. The event gets moved though. 
Not sure if the customfields move ok. Will test that further.

`Error: Call to undefined method CRM_Core_OptionGroup::getValue() in CRM_LCD_MoveParticipant_BAO_MoveParticipant::moveParticipant() (line 22 of /var/www/vhosts/xyz/web/sites/all/modules/civicrm_extensions/biz.lcdservices.moveparticipant/CRM/LCD/MoveParticipant/BAO/MoveParticipant.php).
`
- CiviCRM: 5.66.0
- CMS: Drupal 7.98
- PHP: 8.2.8 (fpm-fcgi)
- Database: 10.11.4-MariaDB-1~deb12u1 engine: InnoDB 10 row format: Dynamic, Compressed
- Webserver: Apache/2.4.57 (Debian)
- OS: Linux

**Comment by lcdservices** [comment]
fixed with version 1.1
